name: Build Docker images
on:
    workflow_dispatch: ~
jobs:
    composer-require-checker_build-parameters:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -
                id: build-parameters
                run: echo "::set-output name=build-parameters::$(cat src/tools/maglnet/composer-require-checker/config/build-parameters.json | tr '\r\n' ' ')"
        outputs:
            build-parameters: ${{ steps.build-parameters.outputs.build-parameters }}

    composer-require-checker:
        name: composer-require-checker
        needs: composer-require-checker_build-parameters
        runs-on: ubuntu-latest
        strategy:
            matrix:
                BUILD_PARAMETERS: ${{ fromJson(needs.composer-require-checker_build-parameters.outputs.build-parameters) }}
        steps:
            - uses: actions/checkout@v2
            -
                uses: ./.github/actions/build-docker-image
                with:
                    DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
                    TOOL_REPOSITORY: maglnet/composer-require-checker
                    BUILD_PARAMETERS: ${{ matrix.BUILD_PARAMETERS }}
