name: Build Docker images
on:
    workflow_dispatch: ~
jobs:
    maglnet_composer-require-checker:
        name: maglnet_composer-require-checker
        runs-on: ubuntu-latest
        strategy:
            matrix:
                TOOL_VERSION: [3.0.0, 3.1.0, 3.2.0, 3.3.1, 3.4.0, 3.5.1, 3.6.0, 3.7.0, 3.8.0, 4.0.0]
        steps:
            - uses: actions/checkout@v2
            -
                uses: ./.github/actions/build-docker-image
                with:
                    DOCKER_HUB_TOKEN: "test me"
                    TOOL_REPOSITORY: maglnet/composer-require-checker
                    TOOL_VERSION: ${{ matrix.TOOL_VERSION }}
